FROM ubuntu:16.04
LABEL maintainer=snhryt

ARG DEBIAN_FRONTEND=noninteractive

# General dependencies
RUN apt-get update \
    && apt-get install -qqy build-essential \
                            cmake \
                            curl \
                            rsync \
                            software-properties-common \
                            wget

# Git
RUN add-apt-repository ppa:git-core/ppa \
    && apt-get update \
    && apt-get install -qqy git

# Boost
ENV BOOST_VERSION=1.65.1
ARG BOOST_DIRNAME=boost_1_65_1
RUN wget https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/${BOOST_DIRNAME}.tar.gz \
    && tar xfz ${BOOST_DIRNAME}.tar.gz \
    && rm ${BOOST_DIRNAME}.tar.gz \
    && cd ${BOOST_DIRNAME} \
    && ./bootstrap.sh \
    && ./b2 --without-python --prefix=/usr -j $(($(nproc) + 1)) link=shared runtime-link=shared install \
    && cd ..  \
    && rm -rf ${BOOST_DIRNAME} \
    && ldconfig

# OpenCV
RUN apt-get install -qqy libgtk2.0-dev \
                         pkg-config \
                         libavcodec-dev \
                         libavformat-dev \
                         libswscale-dev

ARG OPENCV_DIR=/root/opencv
ARG OPENCV_CONTRIB_DIR=/root/opencv_contrib

RUN git clone https://github.com/opencv/opencv.git ${OPENCV_DIR} \
    && git clone https://github.com/opencv/opencv_contrib.git ${OPENCV_CONTRIB_DIR}

RUN cd ${OPENCV_DIR} \
    && mkdir build \
    && cd build \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE \
             -D CMAKE_INSTALL_PREFIX=/usr/local \
             -D OPENCV_EXTRA_MODULES_PATH=${OPENCV_CONTRIB_DIR}/modules \
             .. \
    && make -j $(($(nproc) + 1)) \
    && make install -j $(($(nproc) + 1)) \
    && ldconfig \
    && cd /root \
    && rm -rf opencv opencv_contrib
